//
//  SearchUserDummy.swift
//  GithubSearchTests
//
//  Created by Mephrine on 2020/06/23.
//  Copyright © 2020 Mephrine. All rights reserved.
//

import Foundation
@testable import GithubSearch

struct SearchUserDummy {
    static let jsonData: SearchUser? = jsonStringToData (
        """
        {
          "total_count": 11067,
          "incomplete_results": false,
          "items": [
            {
              "login": "swift",
              "id": 50235,
              "node_id": "MDEyOk9yZ2FuaXphdGlvbjUwMjM1",
              "avatar_url": "https://avatars2.githubusercontent.com/u/50235?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swift",
              "html_url": "https://github.com/swift",
              "followers_url": "https://api.github.com/users/swift/followers",
              "following_url": "https://api.github.com/users/swift/following{/other_user}",
              "gists_url": "https://api.github.com/users/swift/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swift/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swift/subscriptions",
              "organizations_url": "https://api.github.com/users/swift/orgs",
              "repos_url": "https://api.github.com/users/swift/repos",
              "events_url": "https://api.github.com/users/swift/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swift/received_events",
              "type": "Organization",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "theycallmeswift",
              "id": 434373,
              "node_id": "MDQ6VXNlcjQzNDM3Mw==",
              "avatar_url": "https://avatars3.githubusercontent.com/u/434373?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/theycallmeswift",
              "html_url": "https://github.com/theycallmeswift",
              "followers_url": "https://api.github.com/users/theycallmeswift/followers",
              "following_url": "https://api.github.com/users/theycallmeswift/following{/other_user}",
              "gists_url": "https://api.github.com/users/theycallmeswift/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/theycallmeswift/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/theycallmeswift/subscriptions",
              "organizations_url": "https://api.github.com/users/theycallmeswift/orgs",
              "repos_url": "https://api.github.com/users/theycallmeswift/repos",
              "events_url": "https://api.github.com/users/theycallmeswift/events{/privacy}",
              "received_events_url": "https://api.github.com/users/theycallmeswift/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "SwiftOnSecurity",
              "id": 25470060,
              "node_id": "MDQ6VXNlcjI1NDcwMDYw",
              "avatar_url": "https://avatars3.githubusercontent.com/u/25470060?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/SwiftOnSecurity",
              "html_url": "https://github.com/SwiftOnSecurity",
              "followers_url": "https://api.github.com/users/SwiftOnSecurity/followers",
              "following_url": "https://api.github.com/users/SwiftOnSecurity/following{/other_user}",
              "gists_url": "https://api.github.com/users/SwiftOnSecurity/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/SwiftOnSecurity/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/SwiftOnSecurity/subscriptions",
              "organizations_url": "https://api.github.com/users/SwiftOnSecurity/orgs",
              "repos_url": "https://api.github.com/users/SwiftOnSecurity/repos",
              "events_url": "https://api.github.com/users/SwiftOnSecurity/events{/privacy}",
              "received_events_url": "https://api.github.com/users/SwiftOnSecurity/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "brianamarie",
              "id": 9906718,
              "node_id": "MDQ6VXNlcjk5MDY3MTg=",
              "avatar_url": "https://avatars1.githubusercontent.com/u/9906718?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/brianamarie",
              "html_url": "https://github.com/brianamarie",
              "followers_url": "https://api.github.com/users/brianamarie/followers",
              "following_url": "https://api.github.com/users/brianamarie/following{/other_user}",
              "gists_url": "https://api.github.com/users/brianamarie/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/brianamarie/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/brianamarie/subscriptions",
              "organizations_url": "https://api.github.com/users/brianamarie/orgs",
              "repos_url": "https://api.github.com/users/brianamarie/repos",
              "events_url": "https://api.github.com/users/brianamarie/events{/privacy}",
              "received_events_url": "https://api.github.com/users/brianamarie/received_events",
              "type": "User",
              "site_admin": true,
              "score": 1.0
            },
            {
              "login": "ipader",
              "id": 373016,
              "node_id": "MDQ6VXNlcjM3MzAxNg==",
              "avatar_url": "https://avatars3.githubusercontent.com/u/373016?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/ipader",
              "html_url": "https://github.com/ipader",
              "followers_url": "https://api.github.com/users/ipader/followers",
              "following_url": "https://api.github.com/users/ipader/following{/other_user}",
              "gists_url": "https://api.github.com/users/ipader/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/ipader/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/ipader/subscriptions",
              "organizations_url": "https://api.github.com/users/ipader/orgs",
              "repos_url": "https://api.github.com/users/ipader/repos",
              "events_url": "https://api.github.com/users/ipader/events{/privacy}",
              "received_events_url": "https://api.github.com/users/ipader/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "SwiftyWang",
              "id": 14899510,
              "node_id": "MDQ6VXNlcjE0ODk5NTEw",
              "avatar_url": "https://avatars3.githubusercontent.com/u/14899510?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/SwiftyWang",
              "html_url": "https://github.com/SwiftyWang",
              "followers_url": "https://api.github.com/users/SwiftyWang/followers",
              "following_url": "https://api.github.com/users/SwiftyWang/following{/other_user}",
              "gists_url": "https://api.github.com/users/SwiftyWang/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/SwiftyWang/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/SwiftyWang/subscriptions",
              "organizations_url": "https://api.github.com/users/SwiftyWang/orgs",
              "repos_url": "https://api.github.com/users/SwiftyWang/repos",
              "events_url": "https://api.github.com/users/SwiftyWang/events{/privacy}",
              "received_events_url": "https://api.github.com/users/SwiftyWang/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "SwiftArchitect",
              "id": 4073988,
              "node_id": "MDQ6VXNlcjQwNzM5ODg=",
              "avatar_url": "https://avatars0.githubusercontent.com/u/4073988?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/SwiftArchitect",
              "html_url": "https://github.com/SwiftArchitect",
              "followers_url": "https://api.github.com/users/SwiftArchitect/followers",
              "following_url": "https://api.github.com/users/SwiftArchitect/following{/other_user}",
              "gists_url": "https://api.github.com/users/SwiftArchitect/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/SwiftArchitect/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/SwiftArchitect/subscriptions",
              "organizations_url": "https://api.github.com/users/SwiftArchitect/orgs",
              "repos_url": "https://api.github.com/users/SwiftArchitect/repos",
              "events_url": "https://api.github.com/users/SwiftArchitect/events{/privacy}",
              "received_events_url": "https://api.github.com/users/SwiftArchitect/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "swiftix",
              "id": 15327066,
              "node_id": "MDQ6VXNlcjE1MzI3MDY2",
              "avatar_url": "https://avatars0.githubusercontent.com/u/15327066?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swiftix",
              "html_url": "https://github.com/swiftix",
              "followers_url": "https://api.github.com/users/swiftix/followers",
              "following_url": "https://api.github.com/users/swiftix/following{/other_user}",
              "gists_url": "https://api.github.com/users/swiftix/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swiftix/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swiftix/subscriptions",
              "organizations_url": "https://api.github.com/users/swiftix/orgs",
              "repos_url": "https://api.github.com/users/swiftix/repos",
              "events_url": "https://api.github.com/users/swiftix/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swiftix/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "swiftma",
              "id": 3303303,
              "node_id": "MDQ6VXNlcjMzMDMzMDM=",
              "avatar_url": "https://avatars3.githubusercontent.com/u/3303303?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swiftma",
              "html_url": "https://github.com/swiftma",
              "followers_url": "https://api.github.com/users/swiftma/followers",
              "following_url": "https://api.github.com/users/swiftma/following{/other_user}",
              "gists_url": "https://api.github.com/users/swiftma/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swiftma/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swiftma/subscriptions",
              "organizations_url": "https://api.github.com/users/swiftma/orgs",
              "repos_url": "https://api.github.com/users/swiftma/repos",
              "events_url": "https://api.github.com/users/swiftma/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swiftma/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "sindresorhus",
              "id": 170270,
              "node_id": "MDQ6VXNlcjE3MDI3MA==",
              "avatar_url": "https://avatars1.githubusercontent.com/u/170270?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/sindresorhus",
              "html_url": "https://github.com/sindresorhus",
              "followers_url": "https://api.github.com/users/sindresorhus/followers",
              "following_url": "https://api.github.com/users/sindresorhus/following{/other_user}",
              "gists_url": "https://api.github.com/users/sindresorhus/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/sindresorhus/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/sindresorhus/subscriptions",
              "organizations_url": "https://api.github.com/users/sindresorhus/orgs",
              "repos_url": "https://api.github.com/users/sindresorhus/repos",
              "events_url": "https://api.github.com/users/sindresorhus/events{/privacy}",
              "received_events_url": "https://api.github.com/users/sindresorhus/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "benswift",
              "id": 380241,
              "node_id": "MDQ6VXNlcjM4MDI0MQ==",
              "avatar_url": "https://avatars3.githubusercontent.com/u/380241?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/benswift",
              "html_url": "https://github.com/benswift",
              "followers_url": "https://api.github.com/users/benswift/followers",
              "following_url": "https://api.github.com/users/benswift/following{/other_user}",
              "gists_url": "https://api.github.com/users/benswift/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/benswift/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/benswift/subscriptions",
              "organizations_url": "https://api.github.com/users/benswift/orgs",
              "repos_url": "https://api.github.com/users/benswift/repos",
              "events_url": "https://api.github.com/users/benswift/events{/privacy}",
              "received_events_url": "https://api.github.com/users/benswift/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "itplanes",
              "id": 11470917,
              "node_id": "MDQ6VXNlcjExNDcwOTE3",
              "avatar_url": "https://avatars2.githubusercontent.com/u/11470917?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/itplanes",
              "html_url": "https://github.com/itplanes",
              "followers_url": "https://api.github.com/users/itplanes/followers",
              "following_url": "https://api.github.com/users/itplanes/following{/other_user}",
              "gists_url": "https://api.github.com/users/itplanes/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/itplanes/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/itplanes/subscriptions",
              "organizations_url": "https://api.github.com/users/itplanes/orgs",
              "repos_url": "https://api.github.com/users/itplanes/repos",
              "events_url": "https://api.github.com/users/itplanes/events{/privacy}",
              "received_events_url": "https://api.github.com/users/itplanes/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "swiftcafex",
              "id": 13036189,
              "node_id": "MDQ6VXNlcjEzMDM2MTg5",
              "avatar_url": "https://avatars0.githubusercontent.com/u/13036189?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swiftcafex",
              "html_url": "https://github.com/swiftcafex",
              "followers_url": "https://api.github.com/users/swiftcafex/followers",
              "following_url": "https://api.github.com/users/swiftcafex/following{/other_user}",
              "gists_url": "https://api.github.com/users/swiftcafex/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swiftcafex/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swiftcafex/subscriptions",
              "organizations_url": "https://api.github.com/users/swiftcafex/orgs",
              "repos_url": "https://api.github.com/users/swiftcafex/repos",
              "events_url": "https://api.github.com/users/swiftcafex/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swiftcafex/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "RinniSwift",
              "id": 41022840,
              "node_id": "MDQ6VXNlcjQxMDIyODQw",
              "avatar_url": "https://avatars1.githubusercontent.com/u/41022840?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/RinniSwift",
              "html_url": "https://github.com/RinniSwift",
              "followers_url": "https://api.github.com/users/RinniSwift/followers",
              "following_url": "https://api.github.com/users/RinniSwift/following{/other_user}",
              "gists_url": "https://api.github.com/users/RinniSwift/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/RinniSwift/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/RinniSwift/subscriptions",
              "organizations_url": "https://api.github.com/users/RinniSwift/orgs",
              "repos_url": "https://api.github.com/users/RinniSwift/repos",
              "events_url": "https://api.github.com/users/RinniSwift/events{/privacy}",
              "received_events_url": "https://api.github.com/users/RinniSwift/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "johndpope",
              "id": 289994,
              "node_id": "MDQ6VXNlcjI4OTk5NA==",
              "avatar_url": "https://avatars2.githubusercontent.com/u/289994?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/johndpope",
              "html_url": "https://github.com/johndpope",
              "followers_url": "https://api.github.com/users/johndpope/followers",
              "following_url": "https://api.github.com/users/johndpope/following{/other_user}",
              "gists_url": "https://api.github.com/users/johndpope/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/johndpope/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/johndpope/subscriptions",
              "organizations_url": "https://api.github.com/users/johndpope/orgs",
              "repos_url": "https://api.github.com/users/johndpope/repos",
              "events_url": "https://api.github.com/users/johndpope/events{/privacy}",
              "received_events_url": "https://api.github.com/users/johndpope/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "swiftdiaries",
              "id": 23024031,
              "node_id": "MDQ6VXNlcjIzMDI0MDMx",
              "avatar_url": "https://avatars0.githubusercontent.com/u/23024031?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swiftdiaries",
              "html_url": "https://github.com/swiftdiaries",
              "followers_url": "https://api.github.com/users/swiftdiaries/followers",
              "following_url": "https://api.github.com/users/swiftdiaries/following{/other_user}",
              "gists_url": "https://api.github.com/users/swiftdiaries/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swiftdiaries/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swiftdiaries/subscriptions",
              "organizations_url": "https://api.github.com/users/swiftdiaries/orgs",
              "repos_url": "https://api.github.com/users/swiftdiaries/repos",
              "events_url": "https://api.github.com/users/swiftdiaries/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swiftdiaries/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "swiftboard",
              "id": 3633363,
              "node_id": "MDQ6VXNlcjM2MzMzNjM=",
              "avatar_url": "https://avatars3.githubusercontent.com/u/3633363?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swiftboard",
              "html_url": "https://github.com/swiftboard",
              "followers_url": "https://api.github.com/users/swiftboard/followers",
              "following_url": "https://api.github.com/users/swiftboard/following{/other_user}",
              "gists_url": "https://api.github.com/users/swiftboard/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swiftboard/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swiftboard/subscriptions",
              "organizations_url": "https://api.github.com/users/swiftboard/orgs",
              "repos_url": "https://api.github.com/users/swiftboard/repos",
              "events_url": "https://api.github.com/users/swiftboard/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swiftboard/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "swift1911",
              "id": 9301003,
              "node_id": "MDQ6VXNlcjkzMDEwMDM=",
              "avatar_url": "https://avatars3.githubusercontent.com/u/9301003?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swift1911",
              "html_url": "https://github.com/swift1911",
              "followers_url": "https://api.github.com/users/swift1911/followers",
              "following_url": "https://api.github.com/users/swift1911/following{/other_user}",
              "gists_url": "https://api.github.com/users/swift1911/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swift1911/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swift1911/subscriptions",
              "organizations_url": "https://api.github.com/users/swift1911/orgs",
              "repos_url": "https://api.github.com/users/swift1911/repos",
              "events_url": "https://api.github.com/users/swift1911/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swift1911/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "swiftingio",
              "id": 16627606,
              "node_id": "MDQ6VXNlcjE2NjI3NjA2",
              "avatar_url": "https://avatars2.githubusercontent.com/u/16627606?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/swiftingio",
              "html_url": "https://github.com/swiftingio",
              "followers_url": "https://api.github.com/users/swiftingio/followers",
              "following_url": "https://api.github.com/users/swiftingio/following{/other_user}",
              "gists_url": "https://api.github.com/users/swiftingio/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/swiftingio/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/swiftingio/subscriptions",
              "organizations_url": "https://api.github.com/users/swiftingio/orgs",
              "repos_url": "https://api.github.com/users/swiftingio/repos",
              "events_url": "https://api.github.com/users/swiftingio/events{/privacy}",
              "received_events_url": "https://api.github.com/users/swiftingio/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            },
            {
              "login": "sdossettswift",
              "id": 16930414,
              "node_id": "MDQ6VXNlcjE2OTMwNDE0",
              "avatar_url": "https://avatars1.githubusercontent.com/u/16930414?v=4",
              "gravatar_id": "",
              "url": "https://api.github.com/users/sdossettswift",
              "html_url": "https://github.com/sdossettswift",
              "followers_url": "https://api.github.com/users/sdossettswift/followers",
              "following_url": "https://api.github.com/users/sdossettswift/following{/other_user}",
              "gists_url": "https://api.github.com/users/sdossettswift/gists{/gist_id}",
              "starred_url": "https://api.github.com/users/sdossettswift/starred{/owner}{/repo}",
              "subscriptions_url": "https://api.github.com/users/sdossettswift/subscriptions",
              "organizations_url": "https://api.github.com/users/sdossettswift/orgs",
              "repos_url": "https://api.github.com/users/sdossettswift/repos",
              "events_url": "https://api.github.com/users/sdossettswift/events{/privacy}",
              "received_events_url": "https://api.github.com/users/sdossettswift/received_events",
              "type": "User",
              "site_admin": false,
              "score": 1.0
            }
          ]
        }
        """
    )
}

